// backend/src/services/riskService.js
const fs = require("fs");
const path = require("path");

const weatherService = require("./weatherService");

// Load weather baselines (generated by make_baselines.py)
const baselinePath = path.join(__dirname, "../../data/weather_baselines.json");
let weatherBaselines = {};
try {
  weatherBaselines = JSON.parse(fs.readFileSync(baselinePath, "utf8"));
} catch (err) {
  console.error("⚠️ Could not load weather baselines:", err.message);
}
